### ISSUE TITLE
help with iteration argument

### ISSUE THREAD

**Issue by era127** [MikhailKravets/NeuroFlow#9]
Hi, I was wondering if you could explain the iterations argument and the solver.  Is the iterations, the number of times the dataset is sampled with an individual row, or is iterations the number of pass through the whole data set?  So if the dataset has 10_000 rows, iterations = 10_000 would imply the dataset would be sampled 10000 times with batchsize = 1 row?

From what I understood in the code, the rand() call in train() only selected one row per iteration.  

Also I wanted to confirm that the error is cumulative for all iterations, especially if you call train() multiple times in a loop.

Thanks

**Comment by MikhailKravets** [comment]
Hi @rdavis120,

Yes, your understanding is correct. The training algorithm retrieves one random item per training iteration.

Regarding the error, it is zeroed during each backward step (see [`FeedForward::backward`](https://github.com/MikhailKravets/NeuroFlow/blob/c4df80b036b79aeb896e8ce7aab90eb8deb45f42/src/lib.rs#L370) method). So, when you then call the `get_error` method, it returns the latest error of the network.

Let me know if you have further questions.

**Comment by MikhailKravets** [comment]
I assume, after all this time, the issue is resolved.
